name: 'Split Tracker'
author: 'Sebastian Arrubia (sarrubia)'
description: 'Tracks Split events into your Github Actions'
inputs:
  api-key:  # Split api key
    description: 'Split API key'
    required: true
    default: ''
  key:  # user/evaluation key
    description: 'Evaluation key'
    required: true
    default: ''
  traffic-type:  # usually user or account
    description: 'Traffic type'
    required: true
    default: ''
  events:  # custom events to track
    description: 'Events to be tracked'
    required: true
    default: ''

runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'git-merge'  
  color: 'blue'
